services:
  opencode-server:
    image: ghcr.io/anomalyco/opencode
    container_name: opencode-server
    restart: unless-stopped
    networks:
      - agent
    ports:
      - "6144:6144"
    working_dir: /opencode
    volumes:
      # config files
      - ./configs/opencode.json:/root/.config/opencode/opencode.json
      - ./configs/auth.json:/root/.local/share/opencode/auth.json
      # storage
      - ./share:/root/.local/share/opencode/
      - ./cache:/root/.cache/opencode/
      - ./workdir:/opencode
    environment:
      - HTTP_PROXY=http://ops.yl.c8g.top:7890
      - HTTPS_PROXY=http://ops.yl.c8g.top:7890
    command:
      - serve
      - --hostname
      - 0.0.0.0
      - --port
      - "6144"
      - --cors
      - http://opencode-server:6144

  agent-bridge:
    image: agent-bridge:local
    build:
      context: .
      dockerfile: Containerfile
    container_name: agent-bridge
    restart: unless-stopped
    depends_on:
      - opencode-server
    networks:
      - agent
    ports:
      - "9099:9099"
    volumes:
      - ./configs/config.container.yaml:/app/configs/config.yaml:ro
    command:
      - -c
      - /app/configs/config.yml

networks:
  agent:
    driver: bridge
