log:
  handlers:
    default: "default"
  providers:
    default:
      - format: "json"
        level: "debug"
        verbosity: 3
        output:
          stdout:
            enable: true

plugins:
  openai-compatible:
    openai-compatible:
      listen: ":8192"

opencode:
  baseurl: "http://127.0.0.1:4096"
  username: ""
  password: ""
